### ISSUE TITLE
Script without Modbus

### ISSUE THREAD

**Issue by emse1981** [LavermanJJ/pysolarfocus#26]
I own the 5,7 inch eco manager touch from solarfocus with newest software. Unfortunately, modbus is not possible with the old 5,7 inch. But I can access all the data via the app. is there a way to parse the values ​​this way?
E.g. kleinrotti/py-senertec Python Script.
This script retrieves the data via the portal. maybe there is a possibility here too
I hope you can help me.
Thank you

**Comment by LavermanJJ** [comment]
I assume that there is an API one could use. However, I'm not aware that it is public nor did I see any documentation. So I would encourage you to check with the Solarfocus support what their plans about such API is.

Nevertheless, even if the API would be publicly available, this particular repository will not be of much help as it will be completely different, so a new python client lib would need to be developed. 

Sorry
