### ISSUE TITLE
Switch to object oriented data model

### ISSUE THREAD

**Issue by LLukas22** [LavermanJJ/pysolarfocus#6]
To make the api more flexible and expandable i propose to transition the data model from dictionaries to an object oriented model.

For each component of the heatingsystem a abstraction would be created e.g.
```
class Buffer(Component):
    def __init__(self) -> None:
        super().__init__(1900, 5, RegisterTypes.Input)
        self.top_temperature = DataValue(address=0,multiplier=0.1)
        self.bottom_temperature = DataValue(address=1,multiplier=0.1)
        self.pump = DataValue(address=2)
        self.state = DataValue(address=3,type=DataTypes.UINT)
        self.mode = DataValue(address=4,type=DataTypes.UINT)
```
These abstractions will get the modbus address and the range to read from, as well as the register to read from.
They also contain all the sensors as "Value" properties. These **DataValue** objects contain the realtive address/multiplier and datatype.
A **parse()** function will take the raw modbus data as an input and assign the correctly parsed values to all the defined  **DataValue** properties.

Implemented like that we could access all components of the heating system easily without the need for getter methodes e.g.:

```
api = SolarfocusAPI(client)
api.update()

print(f"Top Temp: {api.boiler.top_temperature.scaled_value}")
print(f"Top Temp Raw: {api.boiler.top_temperature.value}")
``` 

When implementing support for other Solarfocus systems we simply have to build a factory that resolves the correct components.

**Comment by LavermanJJ** [comment]
I'm only on mobile and my first impression is very positive. two remarks:

1. I did not fully understand how we account now for the different register maps. Would we provide multiple implementations of the `Buffer` class? And would we select on API init which implementations to use?

2. the home-assistant integration accesses the values by means of their name i.e. entity Key equals property name. If possible we should strive for keeping that stable. But so far this seems given.

**Comment by LLukas22** [comment]
I already created some of the component classes in my [fork](https://github.com/LLukas22/pysolarfocus/blob/main/pysolarfocus/const.py#L152). The basic idea was to unify the input and holding registers into a single abstraction for every component.
If you want you could take a look, but its not finished yet.

1. Answer: If the buffers are completely different then yes we need to provide different implementations. If only some addresses diverge or we need an offset we could handle it in the init of the component. In the initialization we then could choose the implementation we need. For components that are not shared between systems we dont need multiple implementations.
2. Answer: I've looked into your implementation and you mostly access the values via the api methodes to keep compatability i just need to adjust the methodes implemented in the api (e.g. [here](https://github.com/LLukas22/pysolarfocus/blob/main/pysolarfocus/__init__.py#L389)). If i missed anything let me know.

**Comment by LLukas22** [comment]
@LavermanJJ Regarding the `init()` function i would just pass an enum, depending on the passed value the components will be constructed.
At the moment this enum would contain two values: *Vampair* and *Therminator* with *Vampair* beeing the default.


In my oppinion all components should be initialized even if they dont exist in the system, because we still have to keep compatability with the existing homeassistant implementation. For performance reasons only components selected by the user should be updated. But that has to be implemented in the homeassistant integration.

**Comment by LavermanJJ** [comment]
Fixed in https://github.com/LavermanJJ/pysolarfocus/releases/tag/v2.0.0
